spring:
  application:
    name: archivierungsservice

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: archiv-gruppe
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8083
